language: python
python:
- '2.7'
install:
- pip install flake8
before_script:
- flake8 --version
- flake8 --ignore=E501 lambda/
script:
- ./build.sh
deploy:
  provider: releases
  api_key:
    secure: aH1B/BTpLkEvRKFsCCyWTxGYWOT5+09O0zWdiT8QSzDGjHWRk1OIz0YlzamIP11PnGM17hSJUTayWZMDcAeaVAqZavE8bxHfKfq2kuSKyXy47JLeuP9+3tomB3sSoJkgZgE/kCQlOoT3uKQJwZGcHabk/EzK7zvacUZKzwmiFMyReLOCVkhc6u1jKiTJWPe4BImWQOee71CogBxSkFOf/sF4vxAEdcD8FPXFxvpP8lIk1i8l3DMVf8UCb9ttiZJyl63o64+LDVTxnc96bOVwlcS0Lisz5yWFSstbsiD1Asj5yy1MqUqod8f1V+4tXHKLUM7crD6VVEWDG/jI9zig3I0RJQ0xLdV6E47nCv4BQchqywOo4BBHzYaiSi0rFdolSEVG3os0x6hTuEG0ybmFyNfKYdqf4vPV0JFoNPmjfTdlywZaoh2kOY5I7IQVtJsc2j60xKGzpGSBUlF3BE4tNBpfeMF684utLzliNTlXFvpHLSRur7L66XtzhcRdKe1w4Mdiu+Sy/MkqYytMO34NmrVhSkC8D3esoMwiZeYM2sir+r0CzOQ7awPD0OKcpiLX9XuvSDYMBVn7EJfpBCNz0eybcyKFz5o1xZut2JoQbg+KZV3uEeY1yhYAajGa/IapWphcikOdmUYi59GbuVeOtLX8U29Q1N3NlAhogNlL46s=
  file: dist/dynamodb-add-ttl.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: Signiant/dynamodb-add-ttl-lambda
